version: "3" 
services:
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: prepper
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # web:
  #   image: deni/prepper:1
  #   depends_on:
  #     - db
  #   ports:
  #     - "4000:4000"
